version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@reach/dialog"
    versions:
    - 0.13.0
    - 0.13.2
    - 0.14.0
  - dependency-name: "@reach/visually-hidden"
    versions:
    - 0.13.0
    - 0.13.2
    - 0.14.0
  - dependency-name: "@reach/tabs"
    versions:
    - 0.13.0
    - 0.13.2
    - 0.14.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: socket.io
    versions:
    - 2.4.1
